<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>Edge_Dev_x86_Launcher</RootNamespace>
    <AssemblyName>Edge Dev x86 Launcher</AssemblyName>
    <ApplicationIcon>Edge Launcher Dev.ico</ApplicationIcon>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Properties\Settings.Designer.cs" />
    <Compile Include="..\..\Shared\*.cs" Link="Shared\%(Filename)%(Extension)" />
  </ItemGroup>
</Project>
